export const WHICH_BUTTON_IS_ACTIVE = 'WHICH_BUTTON_IS_ACTIVE';
export const FETCH_REQUEST_DEVS = 'FETCH_REQUEST_DEVS';
export const FETCH_REQUEST_LEVELS = 'FETCH_REQUEST_LEVELS';
export const EDITOR_DEV_ENABLE = 'EDITOR_DEV_ENABLE';
export const EDITOR_LEVEL_ENABLE = 'EDITOR_LEVEL_ENABLE';
